### ISSUE TITLE
Path format separator isn't cross-platform compatible

### ISSUE THREAD

**Issue by duh001** [behrendtio/isbin#4]
The path separator appears to be hardcoded to ':', which fails on non-Unix derived operating systems.
The workaround I found was to change line 23 in lib/index.js from
`var paths = process.env.PATH.split(':') || [];`
to
`var paths = process.env.PATH.split(path.delimiter) || [];`
and then add 
`path = require('path')` to the top require section.

Worked for me on Linux, OSX, and Windows.

Pulled from [https://nodejs.org/api/path.html#path_path_delimiter](url)

**Comment by behrendtio** [comment]
Thanks for the catch, fixed in `master` and released as `0.0.3`.
